server:
  port: 9297

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DipRabadiya27/eureka-discovery-service-info
          clone-on-start: true