server:
  port: 8080

spring:
  main:
    web-application-type: REACTIVE
  application:
    name: api-gateway-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DipRabadiya27/eureka-discovery-service-info
          clone-on-start: true